/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Variant({
  'cod' : IDL.Null,
  'chess' : IDL.Null,
  'fortnite' : IDL.Null,
  'valorant' : IDL.Null,
  'roblox' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'avatarSeed' : IDL.Text,
  'rank' : IDL.Nat,
  'playerName' : IDL.Text,
  'points' : IDL.Nat,
});
export const TrainingGuide = IDL.Record({
  'title' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
});
export const MembershipPack = IDL.Record({
  'features' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
});
export const TournamentType = IDL.Variant({
  'solo' : IDL.Null,
  'team' : IDL.Null,
});
export const Tournament = IDL.Record({
  'status' : TournamentStatus,
  'tournamentType' : TournamentType,
  'date' : IDL.Text,
  'game' : Game,
  'name' : IDL.Text,
  'prize' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeaderboards' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Game, IDL.Vec(LeaderboardEntry)))],
      ['query'],
    ),
  'getAllTrainingGuides' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Game, IDL.Vec(TrainingGuide)))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([Game], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMembershipPacks' : IDL.Func([], [IDL.Vec(MembershipPack)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTrainingGuides' : IDL.Func([Game], [IDL.Vec(TrainingGuide)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Variant({
    'cod' : IDL.Null,
    'chess' : IDL.Null,
    'fortnite' : IDL.Null,
    'valorant' : IDL.Null,
    'roblox' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'avatarSeed' : IDL.Text,
    'rank' : IDL.Nat,
    'playerName' : IDL.Text,
    'points' : IDL.Nat,
  });
  const TrainingGuide = IDL.Record({
    'title' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
  });
  const MembershipPack = IDL.Record({
    'features' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
  });
  const TournamentType = IDL.Variant({ 'solo' : IDL.Null, 'team' : IDL.Null });
  const Tournament = IDL.Record({
    'status' : TournamentStatus,
    'tournamentType' : TournamentType,
    'date' : IDL.Text,
    'game' : Game,
    'name' : IDL.Text,
    'prize' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLeaderboards' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Game, IDL.Vec(LeaderboardEntry)))],
        ['query'],
      ),
    'getAllTrainingGuides' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Game, IDL.Vec(TrainingGuide)))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([Game], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMembershipPacks' : IDL.Func([], [IDL.Vec(MembershipPack)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTrainingGuides' : IDL.Func([Game], [IDL.Vec(TrainingGuide)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };