/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Game = { 'cod' : null } |
  { 'chess' : null } |
  { 'fortnite' : null } |
  { 'valorant' : null } |
  { 'roblox' : null };
export interface LeaderboardEntry {
  'avatarSeed' : string,
  'rank' : bigint,
  'playerName' : string,
  'points' : bigint,
}
export interface MembershipPack {
  'features' : string,
  'name' : string,
  'price' : bigint,
}
export interface Tournament {
  'status' : TournamentStatus,
  'tournamentType' : TournamentType,
  'date' : string,
  'game' : Game,
  'name' : string,
  'prize' : string,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'ended' : null };
export type TournamentType = { 'solo' : null } |
  { 'team' : null };
export interface TrainingGuide { 'title' : string, 'tips' : Array<string> }
export interface _SERVICE {
  'getAllLeaderboards' : ActorMethod<
    [],
    Array<[Game, Array<LeaderboardEntry>]>
  >,
  'getAllTrainingGuides' : ActorMethod<[], Array<[Game, Array<TrainingGuide>]>>,
  'getLeaderboard' : ActorMethod<[Game], Array<LeaderboardEntry>>,
  'getMembershipPacks' : ActorMethod<[], Array<MembershipPack>>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getTrainingGuides' : ActorMethod<[Game], Array<TrainingGuide>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];