/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    avatarSeed: string;
    rank: bigint;
    playerName: string;
    points: bigint;
}
export interface TrainingGuide {
    title: string;
    tips: Array<string>;
}
export interface Tournament {
    status: TournamentStatus;
    tournamentType: TournamentType;
    date: string;
    game: Game;
    name: string;
    prize: string;
}
export interface MembershipPack {
    features: string;
    name: string;
    price: bigint;
}
export enum Game {
    cod = "cod",
    chess = "chess",
    fortnite = "fortnite",
    valorant = "valorant",
    roblox = "roblox"
}
export enum TournamentStatus {
    upcoming = "upcoming",
    live = "live",
    ended = "ended"
}
export enum TournamentType {
    solo = "solo",
    team = "team"
}
export interface backendInterface {
    getAllLeaderboards(): Promise<Array<[Game, Array<LeaderboardEntry>]>>;
    getAllTrainingGuides(): Promise<Array<[Game, Array<TrainingGuide>]>>;
    getLeaderboard(game: Game): Promise<Array<LeaderboardEntry>>;
    getMembershipPacks(): Promise<Array<MembershipPack>>;
    getTournaments(): Promise<Array<Tournament>>;
    getTrainingGuides(game: Game): Promise<Array<TrainingGuide>>;
}
import type { Game as _Game, LeaderboardEntry as _LeaderboardEntry, Tournament as _Tournament, TournamentStatus as _TournamentStatus, TournamentType as _TournamentType, TrainingGuide as _TrainingGuide } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllLeaderboards(): Promise<Array<[Game, Array<LeaderboardEntry>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaderboards();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaderboards();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrainingGuides(): Promise<Array<[Game, Array<TrainingGuide>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainingGuides();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainingGuides();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: Game): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_Game_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_Game_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMembershipPacks(): Promise<Array<MembershipPack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipPacks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipPacks();
            return result;
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainingGuides(arg0: Game): Promise<Array<TrainingGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingGuides(to_candid_Game_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingGuides(to_candid_Game_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Game_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentType): TournamentType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TournamentStatus;
    tournamentType: _TournamentType;
    date: string;
    game: _Game;
    name: string;
    prize: string;
}): {
    status: TournamentStatus;
    tournamentType: TournamentType;
    date: string;
    game: Game;
    name: string;
    prize: string;
} {
    return {
        status: from_candid_TournamentStatus_n12(_uploadFile, _downloadFile, value.status),
        tournamentType: from_candid_TournamentType_n14(_uploadFile, _downloadFile, value.tournamentType),
        date: value.date,
        game: from_candid_Game_n3(_uploadFile, _downloadFile, value.game),
        name: value.name,
        prize: value.prize
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Game, Array<_LeaderboardEntry>]): [Game, Array<LeaderboardEntry>] {
    return [
        from_candid_Game_n3(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Game, Array<_TrainingGuide>]): [Game, Array<TrainingGuide>] {
    return [
        from_candid_Game_n3(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    ended: null;
}): TournamentStatus {
    return "upcoming" in value ? TournamentStatus.upcoming : "live" in value ? TournamentStatus.live : "ended" in value ? TournamentStatus.ended : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solo: null;
} | {
    team: null;
}): TournamentType {
    return "solo" in value ? TournamentType.solo : "team" in value ? TournamentType.team : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    chess: null;
} | {
    fortnite: null;
} | {
    valorant: null;
} | {
    roblox: null;
}): Game {
    return "cod" in value ? Game.cod : "chess" in value ? Game.chess : "fortnite" in value ? Game.fortnite : "valorant" in value ? Game.valorant : "roblox" in value ? Game.roblox : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Game, Array<_LeaderboardEntry>]>): Array<[Game, Array<LeaderboardEntry>]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Game, Array<_TrainingGuide>]>): Array<[Game, Array<TrainingGuide>]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Game_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): _Game {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): {
    cod: null;
} | {
    chess: null;
} | {
    fortnite: null;
} | {
    valorant: null;
} | {
    roblox: null;
} {
    return value == Game.cod ? {
        cod: null
    } : value == Game.chess ? {
        chess: null
    } : value == Game.fortnite ? {
        fortnite: null
    } : value == Game.valorant ? {
        valorant: null
    } : value == Game.roblox ? {
        roblox: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
